DROP TABLE InterpreterMission;
DROP TABLE RegularMissionCancelled;
DROP TABLE Mission;
DROP TABLE MissionState;
DROP TABLE JobSkillInterpreter;
DROP TABLE AcademicSkillInterpreter;
DROP TABLE AcademicSkill;
DROP TABLE JobSkill;
DROP TABLE Unavailability;
DROP TABLE Availability;
DROP TABLE TimeSlot;
DROP TABLE BeneficiaryT;
DROP TABLE ManagerT;
DROP TABLE InterpreterT;
DROP TABLE AppliUserT;
DROP TABLE Location;
DROP TABLE City;
DROP TABLE Transportation;
DROP TABLE Status;


CREATE TABLE Status (
    id INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    designation VARCHAR2(25 CHAR) NOT NULL UNIQUE,
    hourQuota INTEGER NOT NULL
);

CREATE TABLE Transportation (
    id INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    designation VARCHAR2(25 CHAR) UNIQUE
);

CREATE TABLE City (
    id INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    designation VARCHAR2 (50 CHAR) NOT NULL,
    postalCode NUMBER(4) NOT NULL
);

CREATE TABLE Location (
    id INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    designation VARCHAR2(50 CHAR),
    city INTEGER NOT NULL REFERENCES City(id) ON DELETE CASCADE,
    street VARCHAR2(50 CHAR) NOT NULL,
    streetNumber VARCHAR2(8 CHAR),
    box INTEGER
);

CREATE TABLE AppliUserT (
    id INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    begin DATE NOT NULL,
    end DATE,
    login VARCHAR2(7 CHAR),
    firstName VARCHAR2(25 CHAR) NOT NULL,
    lastName VARCHAR2(25 CHAR) NOT NULL,
    birthDate DATE NOT NULL,
    hashedPassword VARCHAR2(255 CHAR) NOT NULL,
    email VARCHAR2(50 CHAR) NOT NULL,
    phoneNumber VARCHAR2(25 CHAR),
    passwordUpdated NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE InterpreterT (
    id INTEGER PRIMARY KEY REFERENCES AppliUserT(id) ON DELETE CASCADE,
    weekHourlyQuota INTEGER NOT NULL,
    yearHourlyQuota INTEGER NOT NULL,
    transportMode INTEGER REFERENCES Transportation(id),
    location INTEGER NOT NULL REFERENCES Location(id)
);

CREATE Table ManagerT (
    id INTEGER PRIMARY KEY REFERENCES InterpreterT(id) ON DELETE CASCADE
);

CREATE TABLE BeneficiaryT (
    id INTEGER PRIMARY KEY REFERENCES AppliUserT(id) ON DELETE CASCADE,
    status INTEGER NOT NULL REFERENCES Status(id),
    referenceInterpreter INTEGER NOT NULL REFERENCES InterpreterT(id)
);

CREATE TABLE TimeSlot (
    id INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    startDateTime DATE NOT NULL,
    endDateTime DATE NOT NULL,
    day NUMBER(1)
);

CREATE TABLE Unavailability (
    interpreter INTEGER NOT NULL REFERENCES InterpreterT(id) ON DELETE CASCADE,
    timeSlot INTEGER NOT NULL REFERENCES TimeSlot(id),
    reason VARCHAR2(50 CHAR) NOT NULL,
    CONSTRAINT PKUnavailability PRIMARY KEY (interpreter, timeSlot)
);

CREATE TABLE Availability (
    interpreter INTEGER NOT NULL REFERENCES InterpreterT(id) ON DELETE CASCADE,
    timeSlot INTEGER NOT NULL REFERENCES TimeSlot(id),
    CONSTRAINT PKAvailability PRIMARY KEY (interpreter, timeSlot)
);

CREATE TABLE AcademicSkill (
    id INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    designation VARCHAR2(25 CHAR) NOT NULL UNIQUE
);

CREATE TABLE JobSkill (
    id INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    designation VARCHAR2(25 CHAR) NOT NULL UNIQUE
);

CREATE TABLE AcademicSkillInterpreter (
    interpreter INTEGER NOT NULL REFERENCES InterpreterT(id) ON DELETE CASCADE,
    skill INTEGER NOT NULL REFERENCES AcademicSkill(id) ON DELETE CASCADE,
    CONSTRAINT PKAcademicSkillInterpreter PRIMARY KEY (interpreter, skill)
);

CREATE TABLE JobSkillInterpreter (
    interpreter INTEGER NOT NULL REFERENCES InterpreterT(id) ON DELETE CASCADE,
    skill INTEGER NOT NULL REFERENCES JobSkill(id) ON DELETE CASCADE,
    CONSTRAINT PKJobSkillInterpreter PRIMARY KEY (interpreter, skill)
);

CREATE TABLE MissionState (
    id NUMBER(1) PRIMARY KEY,
    name VARCHAR(15)
);
INSERT INTO MissionState VALUES (0, 'PENDING');
INSERT INTO MissionState VALUES (1, 'ACCEPTED');
INSERT INTO MissionState VALUES (2, 'DENIED');
INSERT INTO MissionState VALUES (3, 'PROGRESSING');
INSERT INTO MissionState VALUES (4, 'REGULAR');
INSERT INTO MissionState VALUES (5, 'CANCELLED');

CREATE TABLE Mission (
    id INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    beneficiary INTEGER REFERENCES BeneficiaryT(id) ON DELETE CASCADE,
    importance NUMBER(1) DEFAULT 0 NOT NULL,
    subject VARCHAR2(50 CHAR) NOT NULL,
    stateOfMission NUMBER(1) DEFAULT 3 NOT NULL REFERENCES MissionState(id),
    commentary VARCHAR2(100 CHAR),
    timeSlot INTEGER NOT NULL REFERENCES TimeSlot(id),
    jobSkill INTEGER REFERENCES JobSkill(id),
    academicSkill INTEGER REFERENCES AcademicSkill(id),
    location INTEGER NOT NULL REFERENCES Location(id),
    room VARCHAR2(25 CHAR)
);

CREATE TABLE RegularMissionCancelled (
    mission INTEGER NOT NULL REFERENCES Mission(id) ON DELETE CASCADE,
    numWeek NUMBER(2) NOT NULL,
    CONSTRAINT PKRegularMissionCancelled PRIMARY KEY (mission, numWeek)
);

CREATE TABLE InterpreterMission (
    mission INTEGER NOT NULL REFERENCES Mission(id) ON DELETE CASCADE,
    interpreter INTEGER NOT NULL REFERENCES InterpreterT(id) ON DELETE CASCADE,
    CONSTRAINT PKInterpreterMission PRIMARY KEY (mission, interpreter)
);


ALTER TABLE Location ADD CONSTRAINT BoxValue CHECK (box IS NULL OR box >= 0);

ALTER TABLE Status ADD CONSTRAINT QuotaValue CHECK (hourQuota >= 0);

ALTER TABLE AppliUserT ADD CONSTRAINT PhoneNumberUser CHECK (phoneNumber IS NULL OR REGEXP_LIKE(phoneNumber,'^[0-9]+\/[0-9]+\.[0-9]+\.[0-9]+$'));
ALTER TABLE AppliUserT ADD CONSTRAINT EmailUser CHECK (REGEXP_LIKE(email, '.+@.+\..+'));

ALTER TABLE InterpreterT ADD CONSTRAINT QuotaWeekValue CHECK (weekHourlyQuota >= 0);
ALTER TABLE InterpreterT ADD CONSTRAINT QuotaYearValue CHECK (yearHourlyQuota >= 0);

ALTER TABLE City ADD CONSTRAINT PostalCodeValue CHECK (postalCode > 999);

ALTER TABLE TimeSlot ADD CONSTRAINT DateOrder CHECK (startDateTime < endDateTime);
ALTER TABLE TimeSlot ADD CONSTRAINT TypeOfTimeSlot CHECK (day IS NULL OR day BETWEEN 1 AND 7);

ALTER TABLE Mission ADD CONSTRAINT ImportanceValue CHECK (importance <= 3);

ALTER TABLE RegularMissionCancelled ADD CONSTRAINT NumWeekValue CHECK (numWeek BETWEEN 1 AND 53);

CREATE OR REPLACE FUNCTION get_heures_prestees(
    interpreter_id IN INTEGER,
    date_debut     IN DATE,
    date_fin       IN DATE
) RETURN NUMBER IS
    total NUMBER;
BEGIN
SELECT SUM((ts.endDateTime - ts.startDateTime) * 24) INTO total
FROM Mission m
JOIN TimeSlot ts ON m.timeSlot = ts.id
JOIN InterpreterMission im ON m.id = im.mission
WHERE im.interpreter = interpreter_id
AND ts.startDateTime >= date_debut
AND ts.endDateTime  <= date_fin
AND m.stateOfMission = 1;

RETURN NVL(total, 0);
END;
/

commit;